#!/bin/bash

branches()
{
	stem="$1"
	git branch -al | sed 's:^..::g' |
		if [ -n "$stem" ]
		then
			grep "^$stem/" | sed "s:^$stem/::g"
		else
			cat
		fi
}

tree_push()
{
	tree=$1; shift;
	remote=$1; shift;
	remote_branch=$1; shift;

	if [ -z "$tree" ] || [ -z "$remote" ] || [ -z "$remote_branch" ]
	then
		echo "tree_push: push local branches to remote" >&2
		echo >&2
		echo "Usage: tree_push <tree> <remote> <remote-branch> [-f]" >&2
		echo "Example: tree_push my_expt origin experimental" >&2
		exit 1
	fi

	if [ "$1" = "-f" ]
	then
		flag="-f"
	else
		flag=""
	fi
	branches=`branches $tree`

	for branch in $branches
	do
		echo === pushing $tree/$branch
		git push $flag $remote $tree/$branch:$remote_branch/$branch
	done
}

`basename $0` $*
