#!/bin/bash

branches()
{
	stem="$1"
	git branch -al | sed 's:^..::g' |
		if [ -n "$stem" ]
		then
			grep "^$stem/" | sed "s:^$stem/::g"
		else
			cat
		fi
}

tree_cp()
{
	from=$1; shift;
	to=$1; shift;

	if [ -z "$from" ] || [ -z "$to" ]
	then
		echo "tree_cp: copy a local tree into another" >&2
		echo >&2
		echo "Usage: tree_cp <from> <to> [-f]" >&2
		echo "   -f: force branch copy" >&2
		exit 1
	fi

	if [ "$1" = "-f" ]
	then
		flag="-f"
	else
		flag=""
	fi

	branches=`branches $from`

	for branch in $branches
	do
		echo === copying $from/$branch to $to/$branch
		git branch $flag $to/$branch $from/$branch
	done
}

`basename $0` $*
